#!/usr/bin/env bash

if
  [[ -s "/home/action/.rvm/gems/ruby-2.0.0-p481@global/environment" ]]
then
  source "/home/action/.rvm/gems/ruby-2.0.0-p481@global/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/gems/ruby-2.0.0-p481@global/environment'" >&2
  exit 1
fi
