#!/usr/bin/env bash

if
  [[ -s "/home/action/.rvm/gems/ruby-2.0.0-p481/environment" ]]
then
  source "/home/action/.rvm/gems/ruby-2.0.0-p481/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/gems/ruby-2.0.0-p481/environment'" >&2
  exit 1
fi
