#!/usr/bin/env bash

if
  [[ -s "/home/action/.rvm/gems/ruby-2.0.0-p481@learn-rails/environment" ]]
then
  source "/home/action/.rvm/gems/ruby-2.0.0-p481@learn-rails/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/gems/ruby-2.0.0-p481@learn-rails/environment'" >&2
  exit 1
fi
